org.dromara.system.api.RemoteClientService=dubbo://localhost:20880
org.dromara.system.api.RemoteLogService=dubbo://localhost:20880
org.dromara.system.api.RemoteDataScopeService=dubbo://localhost:20880
org.dromara.system.api.RemoteDictService=dubbo://localhost:20880
org.dromara.system.api.RemotePermissionService=dubbo://localhost:20880
